
/*
Write a multithreaded program that generates the Fibonacci series. 
The program should work as follows: The user will enter on the command 
line the number of Fibonacci numbers that the program is to generate. 
The program then will create a separate thread that will generate the 
Fibonacci numbers, placing the sequence in data that is shared by the 
threads (an array is probably the most convenient data structure). 
When the thread finishes execution, the parent will output the sequence 
generated by the child thread. Because the parent thread cannot begin 
outputting the Fibonacci sequence until the child thread finishes, 
this will require having the parent thread wait for the child thread to finish.
*/

#include<stdio.h>
#include<stdlib.h>
#include<pthread.h>
 
void* generate_fibonacci(void* param)
{
  // initializing array and values
  int* arr = (int*)param;
  int n = arr[0];
  arr[1] = 0;
  arr[2] = 1;
  
  // creating fibonacci series in array
  for(int i = 3;i <= n;i++)
  {
    arr[i] = arr[i-1] + arr[i-2];
  }
  return NULL;
}
 
int main(int argc, char const *argv[])
{
  // getting the number of fibbonaci number we are to print
  int n;
  printf("Enter no of Fibonacci numbers : \n");
  scanf("%d",&n);
  
  // dynamically initializing our array
  int* arr = (int*)malloc((n+1)*sizeof(int));
  arr[0] = n;
  
  // creating thread 
  pthread_t thread;

  // running routine and passing array
  pthread_create(&thread,0,&generate_fibonacci,(void*)arr);
  
  // joining child threads to the main thread
  pthread_join(thread,0);
  

  // printing out values
  for(int i = 1;i <= n;i++)
    printf("%d ",arr[i]);
  printf("\n");
  
  return 0;
}