# Generated by Django 4.0.3 on 2022-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
